spring:
  datasource:
     url: jdbc:mysql://localhost:3306/gestionstock
     username: root
     password: root
     driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ejb:
          interceptor: gestion_stock.gestionStockapp.interceptor.Intercepteur
  server:
   port: 8081
flickr:
  apiKey: 04eec66d1403e89648e4a0a93b0dd948
  apiSecret: 28e75d25172f143c
  appKey: 72157720867373054-180f4f2d1913e7cb
  appSecret: 21eda3e5ab243bf9
